version: "3.7"
services:
  rclone_mount:
    image: hereisderek/rclone_mergerfs_mounter:latest
    # build:
    #   context: .
    container_name: rclone_mount
    network_mode: bridge
    privileged: true
    security_opt:
      - seccomp:unconfined
    devices:
      - /dev/fuse:/dev/fuse
    ports:
      - 5573:5572
    cap_add:
      - SYS_ADMIN
      - SETPCAP
      - MKNOD
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Pacific/Auckland
      - RC_USER=admin
      - RC_PASS=admin
      - RCLONE_REMOTE=remote01
      - USE_RCD=false #USE_RCD=true isn't working for now
      - RCLONE_EXTRA_PARAMS=-vv # optional
      - RCLONE_CONFIG_FILE_NAME=rclone.conf # optional
      - RC_SERVE=true # optional
      - RC_ENABLE_METRICS=true # optional
      - RCLONE_IP_PORT=:5572 # optional

    volumes:
      - ~/.config/rclone:/config/rclone
      - /path/to/your/rclone/cache:/cache
      - /path/to/your/local/mergerfs:/storage
      # shared modifier is required to see the mounts on the host
      - /path/to/your/mount/parent:/mnt:shared 