version: "3.7"
services:
  rclone_mount:
    image: hereisderek/rclone_mergerfs_mounter:nightly
    build:
      context: .
    container_name: rclone_mount
    privileged: true
    security_opt:
      - seccomp:unconfined
    devices:
      - /dev/fuse:/dev/fuse
    ports:
      - 5572:5572
      - 7879:7879
    cap_add:
      - SYS_ADMIN
      - SETPCAP
      - MKNOD
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Pacific/Auckland
      - RC_USER=admin
      - RC_PASS=admin
      - RCLONE_REMOTE=remote01
      - PARAMS_COMMON_EXTRA=-vv
      - RC_WEB_GUI=true

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config/rclone:/config/rclone
      - /path/to/your/rclone/cache:/cache
      - /path/to/your/local/mergerfs:/storage
      # shared modifier is required to see the mounts on the host
      - /path/to/your/mount/parent:/mnt:shared 